version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    env_file:
      - mongo.env
    volumes:
      - "./mongo-volume:/data/db"
    ports:
      - "27017:27017"
    networks:
      mongonetwork:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-movies
    env_file:
        - .env.development
    volumes: 
      - ".:/app"
    depends_on: 
      - db
    links:
      - db
    networks:
      mongonetwork:
    ports:
      - "3001:3000"
    tty: true
networks:
  mongonetwork:
    driver: bridge